### ISSUE TITLE
Panic when webhook url is invalid 

### ISSUE THREAD

**Issue by Rested** [kubernetes/git-sync#238]
Steps to reproduce:
1. Run
```bash
git-sync --repo=:http://localhost:9000/hook ...etc
```

Output when webhook is triggered
```
0315 20:39:23.155463      12 main.go:379]  "level"=1 "msg"="next sync"  "wait_time"=300000000000
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x8359d6]

goroutine 10 [running]:
main.(*Webhook).Do(0xc000068bc0, 0xc0000268c0, 0x28, 0x0, 0x0)
        /src/cmd/git-sync/webhook.go:75 +0x96
main.(*Webhook).run(0xc000068bc0)
        /src/cmd/git-sync/webhook.go:115 +0x10b
created by main.main
        /src/cmd/git-sync/main.go:335 +0x103e
```

Problem is https://github.com/kubernetes/git-sync/blob/f4fd49cfc759e0c1d7635b2b72aaf29266f52aab/cmd/git-sync/webhook.go#L75 being before the error check.

Solved by pr #239

**Comment by stp-ip** [comment]
Thanks for the report and PR \o/
