### ISSUE TITLE
Error if webhook is set v3.3.5

### ISSUE THREAD

**Issue by DmitriySafronov** [kubernetes/git-sync#474]
**v3.3.5** 

If I set any **webhook** (both in cli and as env var) I've got this in endless cycle:

```
created by main.main
	/src/cmd/git-sync/main.go:492 +0x1765
INFO: detected pid 1, running init handler
I0122 21:37:15.390135      12 main.go:454] "level"=0 "msg"="starting up" "pid"=12 "args"=["/git-sync","--webhook-url=https://home.cyberbrain.pw/api/webhook/reboot"]
I0122 21:37:15.390185      12 main.go:822] "level"=0 "msg"="cloning repo" "origin"="https://gitlab.cyberbrain.pw/infrastructure/deployment-sites/zimniy/home-assistant" "path"="/tmp/git"
panic: duplicate metrics collector registration attempted
goroutine 44 [running]:
github.com/prometheus/client_golang/prometheus.(*Registry).MustRegister(0xc0000be1e0, 0xc0000a0800, 0x1, 0x1)
	/src/vendor/github.com/prometheus/client_golang/prometheus/registry.go:391 +0xad
github.com/prometheus/client_golang/prometheus.MustRegister(...)
	/src/vendor/github.com/prometheus/client_golang/prometheus/registry.go:176
k8s.io/git-sync/pkg/hook.(*HookRunner).Run(0xc000182870, 0x9f0120, 0xc000026038)
	/src/pkg/hook/hook.go:109 +0x91
created by main.main
	/src/cmd/git-sync/main.go:492 +0x1765
INFO: detected pid 1, running init handler
I0122 21:37:15.822954      13 main.go:454] "level"=0 "msg"="starting up" "pid"=13 "args"=["/git-sync","--webhook-url=https://home.cyberbrain.pw/api/webhook/reboot"]
I0122 21:37:15.823014      13 main.go:822] "level"=0 "msg"="cloning repo" "origin"="https://gitlab.cyberbrain.pw/infrastructure/deployment-sites/zimniy/home-assistant" "path"="/tmp/git"
panic: duplicate metrics collector registration attempted
goroutine 50 [running]:
github.com/prometheus/client_golang/prometheus.(*Registry).MustRegister(0xc0000b61e0, 0xc00006f270, 0x1, 0x1)
	/src/vendor/github.com/prometheus/client_golang/prometheus/registry.go:391 +0xad
github.com/prometheus/client_golang/prometheus.MustRegister(...)
	/src/vendor/github.com/prometheus/client_golang/prometheus/registry.go:176
k8s.io/git-sync/pkg/hook.(*HookRunner).Run(0xc0003040c0, 0x9f0120, 0xc000026038)
	/src/pkg/hook/hook.go:109 +0x91
created by main.main
	/src/cmd/git-sync/main.go:492 +0x1765
```
Absolutely all except webhook works perfectly:
```
docker ps --format "{{.Names}}" | grep -q -w git-sync-home-assistant || \
docker run -d \
    --name git-sync-home-assistant \
    --restart always \
    --memory 8m \
    --cpu-shares 10 \
    -u$(id -u):$(id -g) \
    -e GIT_SYNC_REPO="https://.../home-assistant" \
    -e GIT_SYNC_BRANCH="production" \
    -e GIT_SYNC_USERNAME='gitlab+deploy-token-5' \
    -e GIT_SYNC_PASSWORD_FILE="/password" \
    -e GIT_SYNC_DEPTH="1" \
    -e GIT_SYNC_WAIT="30" \
    -e GIT_SYNC_HTTP_METRICS="false" \
    -v "${PWD}/password":/password:Z,ro \
    -v "${PWD}/config":/config:z,rw \
    registry.cyberbrain.pw/docker/git-sync-home-assistant:latest
```

**Comment by thockin** [comment]
Odd, I can't reproduce it.  Are you using my binary git-sync or building your own?

Can you try this:

`docker run -ti k8s.gcr.io/git-sync/git-sync:v3.3.5 -v=5 --repo=https://github.com/thockin/git-sync --depth=1 --root=/tmp/gs --webhook-url=http://google.com`

If that works, try the same with your own image?

Here's what I get
```
$ docker run -ti k8s.gcr.io/git-sync/git-sync:v3.3.5 -v=5 --repo=https://github.com/thockin/git-sync --depth=1 --root=/tmp/gs335 --webhook-url=http://google.com
INFO: detected pid 1, running init handler
I0122 22:04:17.271076      12 main.go:454] "level"=0 "msg"="starting up" "pid"=12 "args"=["/git-sync","-v=5","--repo=https://github.com/thockin/git-sync","--depth=1","--root=/tmp/gs335","--webhook-url=http://google.com"]
I0122 22:04:17.271120      12 main.go:822] "level"=0 "msg"="cloning repo" "origin"="https://github.com/thockin/git-sync" "path"="/tmp/gs335"
I0122 22:04:17.271127      12 cmd.go:48] "level"=5 "msg"="running command" "cwd"="" "cmd"="git clone --no-checkout -b master --depth 1 https://github.com/thockin/git-sync /tmp/gs335"
I0122 22:04:19.018448      12 cmd.go:48] "level"=5 "msg"="running command" "cwd"="/tmp/gs335" "cmd"="git rev-parse HEAD"
I0122 22:04:19.019985      12 main.go:665] "level"=0 "msg"="syncing git" "rev"="HEAD" "hash"="f43e98b2ffb6f93f07656920386e2969a540a8ee"
I0122 22:04:19.020000      12 cmd.go:48] "level"=5 "msg"="running command" "cwd"="/tmp/gs335" "cmd"="git fetch -f --tags --depth 1 origin master"
I0122 22:04:19.776542      12 cmd.go:48] "level"=5 "msg"="running command" "cwd"="/tmp/gs335" "cmd"="git cat-file -t f43e98b2ffb6f93f07656920386e2969a540a8ee"
I0122 22:04:19.778449      12 cmd.go:48] "level"=5 "msg"="running command" "cwd"="/tmp/gs335" "cmd"="git rev-parse f43e98b2ffb6f93f07656920386e2969a540a8ee"
I0122 22:04:19.780170      12 main.go:654] "level"=1 "msg"="removing worktree" "path"="/tmp/gs335/f43e98b2ffb6f93f07656920386e2969a540a8ee"
I0122 22:04:19.780208      12 cmd.go:48] "level"=5 "msg"="running command" "cwd"="/tmp/gs335" "cmd"="git worktree prune"
I0122 22:04:19.781711      12 cmd.go:48] "level"=5 "msg"="running command" "cwd"="/tmp/gs335" "cmd"="git worktree add --detach /tmp/gs335/f43e98b2ffb6f93f07656920386e2969a540a8ee f43e98b2ffb6f93f07656920386e2969a540a8ee --no-checkout"
I0122 22:04:19.786585      12 main.go:700] "level"=0 "msg"="adding worktree" "path"="/tmp/gs335/f43e98b2ffb6f93f07656920386e2969a540a8ee" "branch"="origin/master"
I0122 22:04:19.786597      12 cmd.go:48] "level"=5 "msg"="running command" "cwd"="/tmp/gs335" "cmd"="git gc --prune=all"
I0122 22:04:19.885498      12 cmd.go:48] "level"=5 "msg"="running command" "cwd"="/tmp/gs335/f43e98b2ffb6f93f07656920386e2969a540a8ee" "cmd"="git reset --hard f43e98b2ffb6f93f07656920386e2969a540a8ee"
I0122 22:04:20.014341      12 main.go:766] "level"=0 "msg"="reset worktree to hash" "path"="/tmp/gs335/f43e98b2ffb6f93f07656920386e2969a540a8ee" "hash"="f43e98b2ffb6f93f07656920386e2969a540a8ee"
I0122 22:04:20.014360      12 main.go:771] "level"=0 "msg"="updating submodules"
I0122 22:04:20.014371      12 cmd.go:48] "level"=5 "msg"="running command" "cwd"="/tmp/gs335/f43e98b2ffb6f93f07656920386e2969a540a8ee" "cmd"="git submodule update --init --recursive --depth 1"
I0122 22:04:20.045217      12 main.go:622] "level"=1 "msg"="creating tmp symlink" "root"="/tmp/gs335" "dst"="f43e98b2ffb6f93f07656920386e2969a540a8ee" "src"="tmp-link"
I0122 22:04:20.045237      12 cmd.go:48] "level"=5 "msg"="running command" "cwd"="/tmp/gs335" "cmd"="ln -snf f43e98b2ffb6f93f07656920386e2969a540a8ee tmp-link"
I0122 22:04:20.046572      12 main.go:627] "level"=1 "msg"="renaming symlink" "root"="/tmp/gs335" "old_name"="tmp-link" "new_name"="git-sync"
I0122 22:04:20.046587      12 cmd.go:48] "level"=5 "msg"="running command" "cwd"="/tmp/gs335" "cmd"="mv -T tmp-link git-sync"
I0122 22:04:20.047999      12 cmd.go:48] "level"=5 "msg"="running command" "cwd"="/tmp/gs335" "cmd"="git cat-file -t HEAD"
I0122 22:04:20.048138      12 webhook.go:71] "level"=0 "msg"="sending webhook" "hash"="f43e98b2ffb6f93f07656920386e2969a540a8ee" "url"="http://google.com" "method"="POST" "timeout"=1000000000
I0122 22:04:20.049494      12 cmd.go:48] "level"=5 "msg"="running command" "cwd"="/tmp/gs335" "cmd"="git rev-parse HEAD"
I0122 22:04:20.050675      12 main.go:544] "level"=1 "msg"="next sync" "wait_time"=1000000000
E0122 22:04:20.121108      12 hook.go:124] "msg"="hook failed" "error"="received response code 405 expected 200"
I0122 22:04:21.050903      12 cmd.go:48] "level"=5 "msg"="running command" "cwd"="/tmp/gs335/git-sync" "cmd"="git rev-parse HEAD"
I0122 22:04:21.053073      12 cmd.go:48] "level"=5 "msg"="running command" "cwd"="/tmp/gs335/git-sync" "cmd"="git ls-remote -q origin refs/heads/master"
I0122 22:04:21.498007      12 main.go:962] "level"=1 "msg"="no update required" "rev"="HEAD" "local"="f43e98b2ffb6f93f07656920386e2969a540a8ee" "remote"="f43e98b2ffb6f93f07656920386e2969a540a8ee"
I0122 22:04:21.498079      12 main.go:544] "level"=1 "msg"="next sync" "wait_time"=1000000000
I0122 22:04:22.498298      12 cmd.go:48] "level"=5 "msg"="running command" "cwd"="/tmp/gs335/git-sync" "cmd"="git rev-parse HEAD"
I0122 22:04:22.500542      12 cmd.go:48] "level"=5 "msg"="running command" "cwd"="/tmp/gs335/git-sync" "cmd"="git ls-remote -q origin refs/heads/master"
I0122 22:04:22.968105      12 main.go:962] "level"=1 "msg"="no update required" "rev"="HEAD" "local"="f43e98b2ffb6f93f07656920386e2969a540a8ee" "remote"="f43e98b2ffb6f93f07656920386e2969a540a8ee"
I0122 22:04:22.968148      12 main.go:544] "level"=1 "msg"="next sync" "wait_time"=1000000000
I0122 22:04:23.121315      12 webhook.go:71] "level"=0 "msg"="sending webhook" "hash"="f43e98b2ffb6f93f07656920386e2969a540a8ee" "url"="http://google.com" "method"="POST" "timeout"=1000000000
E0122 22:04:23.192123      12 hook.go:124] "msg"="hook failed" "error"="received response code 405 expected 200"
^C
```

**Comment by thockin** [comment]
Oh, are you ALSO setting exechook?  That could be reaal..

**Comment by DmitriySafronov** [comment]
> Oh, are you ALSO setting exechook? That could be reaal..

Sorry, I've completely forgot some env vars:
```
GIT_SYNC_ROOT='/tmp/git'
GIT_SYNC_DEST='config'
GIT_SYNC_EXECHOOK_COMMAND='/ha-rsync'
```
I'm using my script to rsync Home Assistant config from synced git to docker container with some file exceptions.

And yes, I'm setting both hooks: exechook & webhook

**Comment by thockin** [comment]
OK.  Real bug.  PRs created.  Thanks :)
